OrdererOrgs:
  - Name: Orderer
    Domain: poc2
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
PeerOrgs:
  - Name: Org1
    Domain: org1.poc2
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.poc2
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.poc2
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1