#!/bin/bash
export CHANNEL_NAME=composerchannel
peer channel create -o orderer0.poc2:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/poc2/orderers/orderer0.poc2/msp/tlscacerts/tlsca.poc2-cert.pem
peer channel join -b composerchannel.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.poc2/users/Admin@org1.poc2/msp CORE_PEER_ADDRESS=peer1.org1.poc2:7051 CORE_PEER_LOCALMSPID="Org1MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.poc2/peers/peer1.org1.poc2/tls/ca.crt peer channel join -b composerchannel.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/users/Admin@org2.poc2/msp CORE_PEER_ADDRESS=peer0.org2.poc2:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/peers/peer0.org2.poc2/tls/ca.crt peer channel join -b composerchannel.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/users/Admin@org2.poc2/msp CORE_PEER_ADDRESS=peer1.org2.poc2:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/peers/peer1.org2.poc2/tls/ca.crt peer channel join -b composerchannel.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/users/Admin@org3.poc2/msp CORE_PEER_ADDRESS=peer0.org3.poc2:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/peers/peer0.org3.poc2/tls/ca.crt peer channel join -b composerchannel.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/users/Admin@org3.poc2/msp CORE_PEER_ADDRESS=peer1.org3.poc2:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/peers/peer1.org3.poc2/tls/ca.crt peer channel join -b composerchannel.block
peer channel update -o orderer0.poc2:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org1MSPanchors.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/poc2/orderers/orderer0.poc2/msp/tlscacerts/tlsca.poc2-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/users/Admin@org2.poc2/msp CORE_PEER_ADDRESS=peer0.org2.poc2:7051 CORE_PEER_LOCALMSPID="Org2MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.poc2/peers/peer0.org2.poc2/tls/ca.crt peer channel update -o orderer0.poc2:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org2MSPanchors.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/poc2/orderers/orderer0.poc2/msp/tlscacerts/tlsca.poc2-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/users/Admin@org3.poc2/msp CORE_PEER_ADDRESS=peer0.org3.poc2:7051 CORE_PEER_LOCALMSPID="Org3MSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org3.poc2/peers/peer0.org3.poc2/tls/ca.crt peer channel update -o orderer0.poc2:7050 -c $CHANNEL_NAME -f ./channel-artifacts/Org3MSPanchors.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/poc2/orderers/orderer0.poc2/msp/tlscacerts/tlsca.poc2-cert.pem